/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

/// @file hypre_ams_preconditioner.hpp
/// @brief HYPRE AMS preconditioner wrapper for NGSolve HCurl problems

#ifndef SPARSESOLV_HYPRE_AMS_PRECONDITIONER_HPP
#define SPARSESOLV_HYPRE_AMS_PRECONDITIONER_HPP

#ifdef SPARSESOLV_USE_HYPRE

// Include HYPRE internal utility header for MPI stubs in sequential mode.
// HYPRE_config.h (generated by CMake) defines HYPRE_SEQUENTIAL.
// _hypre_utilities.h includes mpistubs.h which provides MPI_COMM_WORLD etc.
#include "_hypre_utilities.h"
#include "HYPRE.h"
#include "HYPRE_IJ_mv.h"
#include "HYPRE_parcsr_ls.h"

#include <comp.hpp>  // NGSolve
#include <vector>
#include <stdexcept>
#include <iostream>

namespace ngla {

/// HYPRE AMS preconditioner for real HCurl curl-curl + mass systems.
///
/// Wraps HYPRE's AMS (Auxiliary-space Maxwell Solver) for use as an
/// NGSolve BaseMatrix preconditioner. Only supports real (double) matrices.
/// For complex eddy current problems, use Re/Im splitting at the Python level.
class HypreAMSPreconditioner : public BaseMatrix {
public:
    /// Construct HYPRE AMS preconditioner.
    ///
    /// @param mat       System matrix (SparseMatrix<double>, must be nonsymmetric storage)
    /// @param grad_mat  Discrete gradient matrix (HCurl -> H1), from fes.CreateGradient()
    /// @param freedofs  Free DOFs (Dirichlet mask)
    /// @param coords    Vertex coordinates [3][nvertices] (x, y, z)
    /// @param nvertices Number of vertices (= H1 DOFs)
    /// @param cycle_type AMS cycle type (1=additive, 2=mult V-cycle, etc.)
    /// @param print_level HYPRE print level (0=silent, 1=setup, 2+=verbose)
    HypreAMSPreconditioner(
        shared_ptr<SparseMatrix<double>> mat,
        shared_ptr<SparseMatrix<double>> grad_mat,
        shared_ptr<BitArray> freedofs,
        const std::vector<double>& coord_x,
        const std::vector<double>& coord_y,
        const std::vector<double>& coord_z,
        int cycle_type = 1,
        int print_level = 0)
        : mat_(mat), freedofs_(freedofs),
          ndof_hc_(mat->Height()), ndof_h1_(grad_mat->Width())
    {
        if (coord_x.size() != (size_t)ndof_h1_ ||
            coord_y.size() != (size_t)ndof_h1_ ||
            coord_z.size() != (size_t)ndof_h1_)
            throw std::runtime_error("HypreAMS: coordinate vector size mismatch");

        Setup(mat, grad_mat, freedofs, coord_x, coord_y, coord_z,
              cycle_type, print_level);
    }

    ~HypreAMSPreconditioner() {
        Cleanup();
    }

    // BaseMatrix interface
    int VHeight() const override { return ndof_hc_; }
    int VWidth() const override { return ndof_hc_; }
    bool IsComplex() const override { return false; }

    AutoVector CreateRowVector() const override {
        return mat_->CreateRowVector();
    }
    AutoVector CreateColVector() const override {
        return mat_->CreateColVector();
    }

    void Mult(const BaseVector& f, BaseVector& u) const override {
        // Copy NGSolve vector -> HYPRE, zeroing Dirichlet DOFs
        HYPRE_IJVectorInitialize(hyp_b_);
        HYPRE_IJVectorInitialize(hyp_x_);

        auto fv_f = f.FVDouble();
        auto fv_u = u.FVDouble();

        buf_b_.resize(ndof_hc_);
        buf_x_.resize(ndof_hc_);
        for (int i = 0; i < ndof_hc_; i++) {
            // Zero out Dirichlet DOFs in RHS (matches NGSolve's hypre_ams_precond.cpp)
            buf_b_[i] = (freedofs_ && !freedofs_->Test(i)) ? 0.0 : fv_f[i];
            buf_x_[i] = 0.0;
        }

        HYPRE_IJVectorSetValues(hyp_b_, ndof_hc_, indices_hc_.data(), buf_b_.data());
        HYPRE_IJVectorSetValues(hyp_x_, ndof_hc_, indices_hc_.data(), buf_x_.data());

        HYPRE_IJVectorAssemble(hyp_b_);
        HYPRE_IJVectorAssemble(hyp_x_);

        HYPRE_ParVector par_b, par_x;
        HYPRE_IJVectorGetObject(hyp_b_, (void**)&par_b);
        HYPRE_IJVectorGetObject(hyp_x_, (void**)&par_x);

        // Solve
        HYPRE_AMSSolve(precond_, parcsr_A_, par_b, par_x);

        // Copy HYPRE -> NGSolve, zero output first then copy
        HYPRE_IJVectorGetValues(hyp_x_, ndof_hc_, indices_hc_.data(), buf_x_.data());
        fv_u = 0.0;  // Zero everything first
        for (int i = 0; i < ndof_hc_; i++)
            fv_u[i] = buf_x_[i];
    }

    /// MultTrans = Mult for symmetric preconditioner (needed for QMR)
    void MultTrans(const BaseVector& f, BaseVector& u) const override {
        Mult(f, u);
    }

private:
    shared_ptr<SparseMatrix<double>> mat_;
    shared_ptr<BitArray> freedofs_;
    int ndof_hc_, ndof_h1_;

    // HYPRE objects
    HYPRE_Solver precond_ = nullptr;
    HYPRE_IJMatrix hyp_A_ = nullptr;
    HYPRE_ParCSRMatrix parcsr_A_ = nullptr;
    HYPRE_IJMatrix hyp_G_ = nullptr;
    HYPRE_ParCSRMatrix parcsr_G_ = nullptr;
    HYPRE_IJVector hyp_b_ = nullptr;
    HYPRE_IJVector hyp_x_ = nullptr;
    HYPRE_IJVector hyp_coord_[3] = {nullptr, nullptr, nullptr};

    // Index arrays
    std::vector<HYPRE_Int> indices_hc_;
    mutable std::vector<double> buf_b_, buf_x_;

    /// Convert NGSolve SparseMatrix to HYPRE IJ/ParCSR matrix
    void ConvertSparseMatrix(
        const SparseMatrix<double>& ngs_mat,
        const shared_ptr<BitArray>& freedofs,
        int ilower, int iupper,
        HYPRE_IJMatrix& ij_mat, HYPRE_ParCSRMatrix& parcsr_mat,
        bool is_gradient = false)
    {
        int nrows = ngs_mat.Height();
        int ncols = ngs_mat.Width();

        HYPRE_IJMatrixCreate(MPI_COMM_WORLD, ilower, iupper,
                             0, ncols - 1, &ij_mat);
        HYPRE_IJMatrixSetObjectType(ij_mat, HYPRE_PARCSR);
        HYPRE_IJMatrixInitialize(ij_mat);

        // Find max entries per row
        size_t maxperow = 0;
        for (int k = 0; k < nrows; k++)
            maxperow = std::max(maxperow, (size_t)ngs_mat.GetRowIndices(k).Size());

        std::vector<HYPRE_Int> cols(maxperow);
        std::vector<double> vals(maxperow);

        for (int k = 0; k < nrows; k++) {
            auto row_cols = ngs_mat.GetRowIndices(k);
            auto row_vals = ngs_mat.GetRowValues(k);
            HYPRE_Int row = k;
            int s = 0;

            if (is_gradient || !freedofs || freedofs->Test(k)) {
                // Active row: copy all entries
                for (int j = 0; j < row_cols.Size(); j++) {
                    if (!is_gradient && freedofs && !freedofs->Test(row_cols[j]))
                        continue;  // Skip constrained columns for system matrix
                    cols[s] = row_cols[j];
                    vals[s] = row_vals[j];
                    s++;
                }
            } else {
                // Dirichlet row: identity on diagonal
                cols[0] = k;
                vals[0] = 1.0;
                s = 1;
            }

            if (s > 0)
                HYPRE_IJMatrixAddToValues(ij_mat, 1, &s, &row, cols.data(), vals.data());
        }

        HYPRE_IJMatrixAssemble(ij_mat);
        HYPRE_IJMatrixGetObject(ij_mat, (void**)&parcsr_mat);
    }

    /// Create HYPRE IJ vector
    void CreateIJVector(int n, HYPRE_IJVector& vec) {
        HYPRE_IJVectorCreate(MPI_COMM_WORLD, 0, n - 1, &vec);
        HYPRE_IJVectorSetObjectType(vec, HYPRE_PARCSR);
        HYPRE_IJVectorInitialize(vec);
    }

    void Setup(
        shared_ptr<SparseMatrix<double>> mat,
        shared_ptr<SparseMatrix<double>> grad_mat,
        shared_ptr<BitArray> freedofs,
        const std::vector<double>& coord_x,
        const std::vector<double>& coord_y,
        const std::vector<double>& coord_z,
        int cycle_type, int print_level)
    {
        // Index arrays for sequential mode
        indices_hc_.resize(ndof_hc_);
        for (int i = 0; i < ndof_hc_; i++)
            indices_hc_[i] = i;

        // 1. Convert system matrix
        ConvertSparseMatrix(*mat, freedofs, 0, ndof_hc_ - 1,
                            hyp_A_, parcsr_A_, false);

        // 2. Convert gradient matrix (no freedofs filtering)
        ConvertSparseMatrix(*grad_mat, nullptr, 0, ndof_hc_ - 1,
                            hyp_G_, parcsr_G_, true);

        // 3. Create coordinate vectors
        std::vector<HYPRE_Int> indices_h1(ndof_h1_);
        for (int i = 0; i < ndof_h1_; i++)
            indices_h1[i] = i;

        const double* coord_ptrs[3] = {coord_x.data(), coord_y.data(), coord_z.data()};
        HYPRE_ParVector par_coords[3];

        for (int d = 0; d < 3; d++) {
            CreateIJVector(ndof_h1_, hyp_coord_[d]);
            HYPRE_IJVectorSetValues(hyp_coord_[d], ndof_h1_,
                                    indices_h1.data(), coord_ptrs[d]);
            HYPRE_IJVectorAssemble(hyp_coord_[d]);
            HYPRE_IJVectorGetObject(hyp_coord_[d], (void**)&par_coords[d]);
        }

        // 4. Create working vectors
        CreateIJVector(ndof_hc_, hyp_b_);
        {
            std::vector<double> zeros(ndof_hc_, 0.0);
            HYPRE_IJVectorSetValues(hyp_b_, ndof_hc_, indices_hc_.data(), zeros.data());
        }
        HYPRE_IJVectorAssemble(hyp_b_);

        CreateIJVector(ndof_hc_, hyp_x_);
        {
            std::vector<double> zeros(ndof_hc_, 0.0);
            HYPRE_IJVectorSetValues(hyp_x_, ndof_hc_, indices_hc_.data(), zeros.data());
        }
        HYPRE_IJVectorAssemble(hyp_x_);

        // 5. Setup AMS solver
        HYPRE_AMSCreate(&precond_);
        HYPRE_AMSSetDimension(precond_, 3);
        HYPRE_AMSSetPrintLevel(precond_, print_level);
        HYPRE_AMSSetDiscreteGradient(precond_, parcsr_G_);
        HYPRE_AMSSetCoordinateVectors(precond_, par_coords[0], par_coords[1], par_coords[2]);

        // AMS options
        HYPRE_AMSSetTol(precond_, 0);       // Use as preconditioner (no tolerance)
        HYPRE_AMSSetMaxIter(precond_, 1);   // Single V-cycle
        HYPRE_AMSSetCycleType(precond_, cycle_type);

        // Setup with system matrix
        HYPRE_ParVector par_b, par_x;
        HYPRE_IJVectorGetObject(hyp_b_, (void**)&par_b);
        HYPRE_IJVectorGetObject(hyp_x_, (void**)&par_x);
        HYPRE_AMSSetup(precond_, parcsr_A_, par_b, par_x);

        if (print_level > 0)
            std::cout << "  HypreAMS: setup complete (HC=" << ndof_hc_
                      << " H1=" << ndof_h1_ << " cycle=" << cycle_type << ")" << std::endl;
    }

    void Cleanup() {
        if (precond_) { HYPRE_AMSDestroy(precond_); precond_ = nullptr; }
        if (hyp_A_)   { HYPRE_IJMatrixDestroy(hyp_A_); hyp_A_ = nullptr; }
        if (hyp_G_)   { HYPRE_IJMatrixDestroy(hyp_G_); hyp_G_ = nullptr; }
        if (hyp_b_)   { HYPRE_IJVectorDestroy(hyp_b_); hyp_b_ = nullptr; }
        if (hyp_x_)   { HYPRE_IJVectorDestroy(hyp_x_); hyp_x_ = nullptr; }
        for (int d = 0; d < 3; d++)
            if (hyp_coord_[d]) { HYPRE_IJVectorDestroy(hyp_coord_[d]); hyp_coord_[d] = nullptr; }
    }
};

/// Complex HYPRE AMS preconditioner with TaskManager Re/Im parallelism.
///
/// For complex eddy current problems (A = K + jw*sigma*M), applies HYPRE AMS
/// to real and imaginary parts in parallel using NGSolve's TaskManager.
///
/// Uses TWO independent HYPRE AMS solver instances (each with its own
/// internal vectors) so they can execute concurrently without data races.
/// Memory cost: 2x the real AMS solver.
///
/// Usage:
///   auto pre = make_shared<ComplexHypreAMSPreconditioner>(
///       a_real_mat, grad_mat, freedofs, coord_x, coord_y, coord_z,
///       ndof_complex, cycle_type, print_level);
///   // Use with NGSolve's GMResSolver on complex system
class ComplexHypreAMSPreconditioner : public BaseMatrix {
public:
    /// @param a_real_mat   Real auxiliary matrix (SparseMatrix<double>)
    /// @param grad_mat     Discrete gradient matrix
    /// @param freedofs     Free DOFs for HCurl space (real)
    /// @param coord_x/y/z  Vertex coordinates
    /// @param ndof_complex Number of complex DOFs (= real DOFs)
    /// @param cycle_type   AMS cycle type
    /// @param print_level  HYPRE print level
    ComplexHypreAMSPreconditioner(
        shared_ptr<SparseMatrix<double>> a_real_mat,
        shared_ptr<SparseMatrix<double>> grad_mat,
        shared_ptr<BitArray> freedofs,
        const std::vector<double>& coord_x,
        const std::vector<double>& coord_y,
        const std::vector<double>& coord_z,
        int ndof_complex,
        int cycle_type = 1,
        int print_level = 0)
        : ndof_complex_(ndof_complex),
          ndof_real_(a_real_mat->Height())
    {
        // Create TWO independent HYPRE AMS solvers for parallel Re/Im
        ams_re_ = make_shared<HypreAMSPreconditioner>(
            a_real_mat, grad_mat, freedofs,
            coord_x, coord_y, coord_z, cycle_type, print_level);
        ams_im_ = make_shared<HypreAMSPreconditioner>(
            a_real_mat, grad_mat, freedofs,
            coord_x, coord_y, coord_z, cycle_type, 0);  // no double print

        // Allocate real work vectors
        re_in_ = make_unique<VVector<double>>(ndof_real_);
        im_in_ = make_unique<VVector<double>>(ndof_real_);
        re_out_ = make_unique<VVector<double>>(ndof_real_);
        im_out_ = make_unique<VVector<double>>(ndof_real_);

        if (print_level > 0)
            std::cout << "  ComplexHypreAMS: 2 solver instances for TaskManager "
                      << "Re/Im parallelism (ndof=" << ndof_complex_ << ")"
                      << std::endl;
    }

    int VHeight() const override { return ndof_complex_; }
    int VWidth() const override { return ndof_complex_; }
    bool IsComplex() const override { return true; }

    AutoVector CreateRowVector() const override {
        return make_unique<VVector<Complex>>(ndof_complex_);
    }
    AutoVector CreateColVector() const override {
        return make_unique<VVector<Complex>>(ndof_complex_);
    }

    void Mult(const BaseVector& f, BaseVector& u) const override {
        // Split complex input into real and imaginary parts
        auto fv_f = f.FVComplex();
        auto fv_re_in = re_in_->FVDouble();
        auto fv_im_in = im_in_->FVDouble();

        for (int i = 0; i < ndof_real_; i++) {
            fv_re_in[i] = fv_f[i].real();
            fv_im_in[i] = fv_f[i].imag();
        }

        // Apply HYPRE AMS to Re and Im in parallel via TaskManager.
        // Each AMS instance has its own HYPRE vectors, so no data races.
        // TaskManager distributes the 2 tasks across threads.
        // If TaskManager is not active, runs sequentially.
        auto ams_re = ams_re_;
        auto ams_im = ams_im_;
        auto* p_re_in = re_in_.get();
        auto* p_im_in = im_in_.get();
        auto* p_re_out = re_out_.get();
        auto* p_im_out = im_out_.get();

        ParallelFor(2, [=](int task) {
            if (task == 0)
                ams_re->Mult(*p_re_in, *p_re_out);
            else
                ams_im->Mult(*p_im_in, *p_im_out);
        });

        // Combine into complex output
        auto fv_u = u.FVComplex();
        auto fv_re_out = re_out_->FVDouble();
        auto fv_im_out = im_out_->FVDouble();

        for (int i = 0; i < ndof_real_; i++)
            fv_u[i] = Complex(fv_re_out[i], fv_im_out[i]);
    }

    void MultTrans(const BaseVector& f, BaseVector& u) const override {
        Mult(f, u);
    }

private:
    int ndof_complex_;
    int ndof_real_;

    // Two independent HYPRE AMS solvers for thread-safe parallel execution
    shared_ptr<HypreAMSPreconditioner> ams_re_;
    shared_ptr<HypreAMSPreconditioner> ams_im_;

    // Work vectors (owned, not shared)
    mutable unique_ptr<VVector<double>> re_in_, im_in_;
    mutable unique_ptr<VVector<double>> re_out_, im_out_;
};

}  // namespace ngla

#endif  // SPARSESOLV_USE_HYPRE
#endif  // SPARSESOLV_HYPRE_AMS_PRECONDITIONER_HPP
